version: '3'

services:

  concourse-db:
    # build: ./dir
    image: postgres:10.5
    environment:
      POSTGRES_DB: "concourse"
      POSTGRES_PASSWORD: "concourse_pass"
      POSTGRES_USER: "concourse_user"
      PGDATA: "/database"

  concourse-web:
    # build: ./dir
    image: concourse/concourse:4.0.0
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_LOG_LEVEL: "debug"
      CONCOURSE_POSTGRES_HOST: "concourse-db"
      CONCOURSE_POSTGRES_USER: "concourse_user"
      CONCOURSE_POSTGRES_PASSWORD: "concourse_pass"
      CONCOURSE_POSTGRES_DATABASE: "concourse"
      CONCOURSE_BASIC_AUTH_USERNAME: "jeff"
      CONCOURSE_BASIC_AUTH_PASSWORD: "test"
      CONCOURSE_EXTERNAL_URL: "http://192.168.100.5:8080"
      CONCOURSE_PEER_URL:
      CONCOURSE_ADD_LOCAL_USER: "test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW"
      CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS: "true"

  concourse-worker:
    # build: ./dir
    image: concourse/concourse:4.0.0
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: "concourse-web:2222"
      CONCOURSE_GARDEN_NETWORK:
    